name: Lint & Format Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: cd next-app && npm install

      - name: Run ESLint
        run: cd next-app && npx eslint .
        # command: npx eslint --fix

      - name: Run Prettier check
        run: cd next-app && npx prettier . --check
        # command: npx prettier . -w